//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedTestApp.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureEntity
    {
        public int ID { get; set; }
        public int PageID { get; set; }
        public int Result { get; set; }
        public Nullable<System.DateTime> MeasureTime { get; set; }
    
        public virtual PageEntity Page { get; set; }
    }
}
