USE [master]
GO
/****** Object:  Database [SitePerformanceDB]    Script Date: 31.05.2017 9:27:05 ******/
CREATE DATABASE [SitePerformanceDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SitePerformanceDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SitePerformanceDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SitePerformanceDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SitePerformanceDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SitePerformanceDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SitePerformanceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SitePerformanceDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SitePerformanceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SitePerformanceDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SitePerformanceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SitePerformanceDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SitePerformanceDB] SET  MULTI_USER 
GO
ALTER DATABASE [SitePerformanceDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SitePerformanceDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SitePerformanceDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SitePerformanceDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SitePerformanceDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SitePerformanceDB]
GO
/****** Object:  Table [dbo].[Measures]    Script Date: 31.05.2017 9:27:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Measures](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PageID] [int] NOT NULL,
	[Result] [int] NOT NULL,
	[MeasureTime] [datetime2](7) NULL,
 CONSTRAINT [PK_Measures] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Pages]    Script Date: 31.05.2017 9:27:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pages](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SiteID] [int] NOT NULL,
	[Page] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_Pages] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Sites]    Script Date: 31.05.2017 9:27:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sites](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[URL] [nvarchar](50) NULL,
 CONSTRAINT [PK_Sites] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Measures]  WITH CHECK ADD  CONSTRAINT [FK_Measures_Pages] FOREIGN KEY([PageID])
REFERENCES [dbo].[Pages] ([ID])
GO
ALTER TABLE [dbo].[Measures] CHECK CONSTRAINT [FK_Measures_Pages]
GO
ALTER TABLE [dbo].[Pages]  WITH CHECK ADD  CONSTRAINT [FK_Pages_Sites] FOREIGN KEY([SiteID])
REFERENCES [dbo].[Sites] ([ID])
GO
ALTER TABLE [dbo].[Pages] CHECK CONSTRAINT [FK_Pages_Sites]
GO
USE [master]
GO
ALTER DATABASE [SitePerformanceDB] SET  READ_WRITE 
GO
